# Site settings
title: BorealBlizzard - A Software & Hardware Tinkerer
description: "A Place documenting my explorations"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://BorealBlizzard.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: BorealBlizzard
user_title: BorealBlizzard - FrontEnd
email: rapter476@outlook.com
twitter_username: JakobRamen
github_username: BorealBlizzard
gplus_username: 
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: 
profile_picture: "/assets/img/icon1.ico"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/BorealBlizzard
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/JakobRamen
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: This Website
    url: https://github.com/BorealBlizzard/BorealBlizzard.github.io
  - name: FinleyBot Discord bot
    url: https://github.com/BorealBlizzard/FinleyBot

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
